name: Check compat (readonly)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7"]
        cryptography-version: ["3.3.2"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pytest cryptography==${{ matrix.cryptography-version }}

    - name: Check backwards compat reads
      run: pytest -s -v tests/test_backwards_compat.py
