name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up pyproject
      run: |
        pip install -U pip uv
        uv sync --frozen

    - name: Check codebase
      run: uv run inv fmt --check && uv run inv test

    - name: Build
      run: uv run inv build

    - name: Publish to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: uv run inv publish --token "$PYPI_API_TOKEN"
